mysite/api/urls.py
from django.urls import path
from rest_framework.urlpatterns import format_suffix_patterns
from api import views

urlpatterns = [
    # path('snippets/', views.snippet_list),
    # path('snippets/<int:pk>/', views.snippet_detail),
    path('', views.api_root),
    path('snippets/', views.SnippetList.as_view(), name="snippet-list"),
    path('snippets/<int:pk>/', views.SnippetDetail.as_view(), name="snippet-detail"),
    path('users/', views.UserList.as_view(), name="user-list"),
    path('users/<int:pk>/', views.UserDetail.as_view(), name="user-detail"),
    path('posts/', views.PostList.as_view(), name="post-list"),
    path('posts/<int:pk>/', views.PostDetail.as_view(), name="post-detail"),
    path('profile/', views.profile, name="profile"),
    path('login/', views.api_login, name="login"),
]
urlpatterns = format_suffix_patterns(urlpatterns)

mysite/blog/urls.py
from django.http import HttpRequest, HttpResponse
from django.urls import include, path
from django.views.generic import ListView

from . import views
from . import models

app_name = 'blog'

urlpatterns = [
    path('', views.index),
    path('post_list/', views.post_list, name = 'list'),
    path('post_detail/<int:pk>/', views.post_detail, name = 'detail'),
    path('post_create/', views.post_create, name = 'create'),
    path('api/post/', views.api_post_list, name="api_list"),
    path('api/post/<int:pk>/', views.api_post, name="api_one")
]

mysite/mysite/urls.py
# """mysite URL Configuration

# The `urlpatterns` list routes URLs to views. For more information please see:
#     https://docs.djangoproject.com/en/3.2/topics/http/urls/
# Examples:
# Function views
#     1. Add an import:  from my_app import views
#     2. Add a URL to urlpatterns:  path('', views.home, name='home')
# Class-based views
#     1. Add an import:  from other_app.views import Home
#     2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
# Including another URLconf
#     1. Import the include() function: from django.urls import include, path
#     2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
# """
# from django.contrib import admin
# from django.urls import include, path

# urlpatterns = [
#     path('accounts/', include('django.contrib.auth.urls')),
#     path('admin/', admin.site.urls),
#     path('blog/', include('blog.urls'), name="blog"),
#     path('toy/', include('toy.urls'), name="toy"),
#     path('polls/', include('polls.urls'), name="polls"),
#     path('api-auth/', include('rest_framework.urls'))
# ]

from django.urls import path, include, re_path
from django.contrib.auth.models import User
from rest_framework import routers, serializers, viewsets

from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

from django.contrib import admin

schema_view = get_schema_view(
   openapi.Info(
      title="Handong API",
      default_version='v1',
      description="Test description",
      terms_of_service="https://www.google.com/policies/terms/",
      contact=openapi.Contact(email="contact@snippets.local"),
      license=openapi.License(name="BSD License"),
   ),
   public=True,
   permission_classes=[permissions.AllowAny],
)

# Wire up our API using automatic URL routing.
# Additionally, we include login URLs for the browsable API.
urlpatterns = [
    path('', include('allauth.urls')),
    path('admin/', admin.site.urls),
    path('api/', include('api.urls')),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    re_path(r'^swagger(?P<format>\.json|\.yaml)$', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    re_path(r'^swagger/$', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    re_path(r'^redoc/$', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
]

mysite/blog/models.py
from django.db import models

# Create your models here.
class Post(models.Model):
   title = models.CharField(max_length=100)
   content = models.TextField()

mysite/blog/forms.py
from django import forms
from . import models

class PostForm(forms.Form):
    title = forms.CharField(max_length=100)
    content = forms.CharField(widget=forms.Textarea())

class PostModelForm(forms.ModelForm):
    class Meta:
        model = models.Post
        fields = ('title', 'content')

mysite/blog/views.py
from django.http import HttpRequest, HttpResponse, JsonResponse
from django.shortcuts import redirect, render
from . import models
import json

def index(req: HttpRequest) -> HttpResponse:
    return HttpResponse('blog')

def post_list(req):
    posts = models.Post.objects.all()
    return render(req, 'blog/post_list.html', {"post_list": posts})

def post_detail(req, pk):
    post = models.Post.objects.get(pk=pk)
    return render(req, 'blog/post_detail.html', {"post": post})

def post_create(req):
    if req.method == "POST":
        post = models.Post(title=req.POST["title"], content=req.POST['content'])
        post.save()
        return redirect("/blog/post_list/")
    return render(req, 'blog/post_create.html')


def api_post_list(req):
    if req.method =='GET':
        posts = models.Post.objects.all()
        return JsonResponse({"results": list(posts.values())})
    else :
        return HttpResponse(status=405)

from django.forms.models import model_to_dict
def api_post(req, pk):
    if req.method =='GET':
        post =models.Post.objects.get(pk=pk)
        return JsonResponse({"results": model_to_dict(post)})
    else :
        return HttpResponse(status=405)

mysite/blog/templates/blog/post_create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Blog - Post Create</title>
</head>
<body>
    <h1>Post Create</h1>
    <form method="post">
        {% csrf_token %}
        <table>
            {{ form }}
        </table>
        <div><input type="submit" value="저장"></div>
    </form>
</body>
</html>

mysite/blog/templates/blog/post_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Blog - Post Detail</title>
</head>
<body>
    <h1>{{ post.title }}</h1>
    <div>{{ post.content }}</div>
    <hr>
    <a href="{% url 'blog:list' %}">리스트로</a>
</body>
</html>

mysite/blog/templates/blog/post_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Blog - Post List</title>
</head>
<body>
    <h1>Post List</h1>
    <ul>
        {% for p in post_list %}
            <li><a href="{% url 'blog:detail' p.pk %}">{{ forloop.counter }} {{ p.title }}</a></li>
        {% endfor %}
    </ul>
    <hr>
    <a href="{% url 'blog:create' %}">새글쓰기</a>
</body>
</html>